In [1]:
# Spark DataFrame Operations
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('ops').getOrCreate()
print('Spark is Connected')

24/01/09 17:04:17 WARN Utils: Your hostname, MaheshPC resolves to a loopback address: 127.0.1.1; using 192.168.1.7 instead (on interface enp5s0)
24/01/09 17:04:17 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/01/09 17:04:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
24/01/09 17:04:19 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
24/01/09 17:04:19 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
24/01/09 17:04:19 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.

Spark is Connected

In [3]:
df = spark.read.csv('Datasets/appl_stock.csv',inferSchema=True,header=True)
df.show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [4]:
# to print schema
df.printSchema()

root
 |-- Date: date (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [7]:
# to filter

df.filter('Close < 500').select(['Open','High','Low']).show()

+------------------+------------------+------------------+
|              Open|              High|               Low|
+------------------+------------------+------------------+
|        213.429998|        214.499996|212.38000099999996|
|        214.599998|        215.589994|        213.249994|
|        214.379993|            215.23|        210.750004|
|            211.75|        212.000006|        209.050005|
|        210.299994|        212.000006|209.06000500000002|
|212.79999700000002|        213.000002|        208.450005|
|209.18999499999998|209.76999500000002|        206.419998|
|        207.870005|210.92999500000002|        204.099998|
|210.11000299999998|210.45999700000002|        209.020004|
|210.92999500000002|211.59999700000003|        205.869999|
|        208.330002|215.18999900000003|        207.240004|
|        214.910006|        215.549994|        209.500002|
|        212.079994|213.30999599999998|        207.210003|
|206.78000600000001|        207.499996|            197.16|
|202.51000200000001|        204.699999|        200.190002|
|205.95000100000001|        213.710005|        202.580004|
|        206.849995|            210.58|        199.530001|
|        204.930004|        205.500004|        198.699995|
|        201.079996|        202.199995|        190.250002|
|192.36999699999998|             196.0|191.29999899999999|
+------------------+------------------+------------------+
only showing top 20 rows

In [10]:
# to get the column which b/w 200 and 300
df.filter((df['Close']>=200) & (df['Close']<=300)).show()

+----------+------------------+------------------+------------------+------------------+---------+------------------+
|      Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-25|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-02-12|        198.109995|        201.639996|        195.500002|200.37999299999998|163867200|25.961142000000002|
|2010-02-16|        201.940002|        203.690002|        201.520006|        203.399996|135934400|         26.352412|
|2010-02-17|        204.190001|        204.310003|        200.860004|        202.550003|109099200|         26.242287|
|2010-02-18|        201.629995|        203.889994|        200.920006|        202.929998|105706300|         26.291519|
+----------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [12]:

result = df.filter (df [ 'Low'] == 197.16).collect()
result[0]

Row(Date=datetime.date(2010, 1, 22), Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)

In [14]:
# row as dict
r = result[0]
r.asDict()

{'Date': datetime.date(2010, 1, 22),
 'Open': 206.78000600000001,
 'High': 207.499996,
 'Low': 197.16,
 'Close': 197.75,
 'Volume': 220441900,
 'Adj Close': 25.620401}